apiVersion: apps/v1
kind: Deployment
metadata:
  name: bad-deployment
  labels:
    foo: bar
spec:
  selector:
    matchLabels:
      app: nginx-bad
  template:
    metadata:
      labels:
        app: nginx-bad
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
