apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
    costCenterCode: foo
spec:
  template:
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
